[package]
name = "meridian"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.18", features = ["derive"] }
clap = { version = "4.6.0", features = ["derive", "env"] }
enum_dispatch = "0.3.13"
midly = "0.5.3"
rayon = "1.10"
rustc-hash = "2.0.0"
slint = { version = "~1.15", features = [
  "unstable-wgpu-28",
  "backend-winit-x11",
  "backend-winit-wayland",
  "renderer-femtovg",
  "renderer-skia",
  "renderer-software",
] }
thiserror = "2.0.12"
