[workspace]
members = [
    "crates/meridian-core",
    "crates/meridian-stdio",
    "crates/meridian-ui",
]
default-members = ["crates/meridian-stdio", "crates/meridian-ui"]
resolver = "3"

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
bytemuck = { version = "1.18", features = ["derive"] }
clap = { version = "4.6.0", features = ["derive", "env"] }
enum_dispatch = "0.3.13"
flate2 = "1.1.4"
flume = "0.11.1"
glam = "0.30.8"
midi-toolkit-rs = { path = "../midi-toolkit-rs/midi-toolkit" }
midly = "0.5.3"
png = "0.18.0"
pollster = "0.4.0"
rayon = "1.10"
rfd = "0.15"
rustc-hash = "2.0.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
slint = { version = "~1.15", features = [
    "unstable-wgpu-28",
    "unstable-winit-030",
    "backend-winit-x11",
    "backend-winit-wayland",
    "renderer-femtovg",
    "renderer-skia",
    "renderer-software",
] }
thiserror = "2.0.12"
ts-rs = { version = "12.0.1", features = ["no-serde-warnings"] }
wgpu = "28.0.0"
xsynth-core = { path = "../xsynth/core", features = ["serde"] }
xsynth-realtime = { path = "../xsynth/realtime", features = ["serde"] }
xsynth-render = { path = "../xsynth/render" }

[profile.dev]
opt-level = 2
